# CircleCI configuration file
# Based on the official CircleCI documentation and examples on the CircleCI website and YouTube channel.
# https://circleci.com/docs/guides/getting-started/introduction-to-yaml-configurations/
# https://circleci.com/blog/deploy-a-node-app-on-aws-ec2-linux/
# https://www.youtube.com/watch?v=Js3hMUsSZ2c&list=PL9GgS3TcDh8x6tcY7HDq2zmEx0fAtwWsM

version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: npm run test

  deploy:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY}"
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@${HOST} "cd ~/app && git fetch origin && git reset --hard origin/main && npm ci"
            printf '%s\n' "$PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no ec2-user@${HOST} "cat > ~/app/privatekey.pem"
            printf '%s\n' "$SERVER" | ssh -o StrictHostKeyChecking=no ec2-user@${HOST} "cat > ~/app/server.crt"
            ssh -o StrictHostKeyChecking=no ec2-user@${HOST} "cd ~/app && pm2 delete app || true && pm2 start ./bin/www --name app && pm2 save"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main